# Generated by Django 2.2.6 on 2019-12-28 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='cart_value',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='customer',
            name='phone_num',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='customer',
            name='table_num',
            field=models.IntegerField(),
        ),
    ]
