# Generated by Django 2.2.6 on 2019-12-28 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0003_menu'),
    ]

    operations = [
        migrations.AddField(
            model_name='menu',
            name='category',
            field=models.CharField(default='Snacks', max_length=20),
        ),
    ]
