# Generated by Django 2.2.6 on 2019-12-28 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0004_menu_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='menu',
            name='dish_qty',
        ),
        migrations.AddField(
            model_name='menu',
            name='dish_full_price',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='menu',
            name='dish_half_price',
            field=models.IntegerField(default=0),
        ),
    ]
